function Hd = T3
%T3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 20-Apr-2021 15:53:33

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N      = 30;   % Order
Fstop1 = 0.2;  % First Stopband Frequency
Fpass1 = 0.4;  % First Passband Frequency
Fpass2 = 0.6;  % Second Passband Frequency
Fstop2 = 0.8;  % Second Stopband Frequency
Wstop1 = 1;    % First Stopband Weight
Wpass  = 1;    % Passband Weight
Wstop2 = 1;    % Second Stopband Weight
dens   = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 1], [0 0 1 1 0 0], ...
           [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
