function Hd = P1T1Bb
%P1T1BB Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 04-May-2021 17:33:05

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are normalized to 1.

Fstop = 0.2;         % Stopband Frequency
Fpass = 0.4;         % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 1;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
